data:
  dataset:
    name: flickr
    dataset_root: /work/vjsalt22/dataset/flickr/
  batch_size: 32
  dev_batch_size: 4
  split_ratio: 0.9

clip:
  name: ViT-B/32
  image_encoder_trainable: false
  text_encoder_trainable: false

cl_loss:
  temperature: 1
  base_temperature: 1
  contrast_mode: all

retrieval:
  recall_at: [1,5,10]

audio_encoder:
  type: s3prl
  name: hubert
  pretrained: true
  trainable: true
  feat_select_idx: last_hidden_state
  layer_drop: 0.05
  max_audio_len: 138581
  pooling:
    type: attentive_pooling
    degraded: true
    audio_projection_type: pre
  optim:
    name: Adam
    args:
      lr: 1.e-4
      weight_decay: 1.e-6
  scheduler:
    name: linear_warmup_decay
    warmup: 7000
    max_step: 70000
    final_lr: 1.e-8

trainer:
  max_steps: 70000
  gradient_clip_val: 10
  accumulate_grad_batches: 8
  check_val_every_n_epoch: 1
  precision: 16
  logger: true
  default_root_dir: ./exp/sc_p_attPool_degraded
  log_every_n_steps: 2
  num_sanity_val_steps: 0
  # limit_train_batches: 2
  # limit_val_batches: 8


# learnable U
#   | Name                  | Type                    | Params
# 0 | audio_encoder         | S3prlSpeechEncoder      | 94.7 M
# 1 | clip                  | ClipModel               | 151 M 
# 2 | audio_feat_projection | Linear                  | 393 K 
# 3 | audio_pooling         | AttentivePoolingLayer   | 262 K 
# 4 | criterion             | SupConLoss              | 0    
